# Generated by Django 6.0.3 on 2026-09-08 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='store.orderitem'),
        ),
    ]
