# Generated by Django 6.0.3 on 2026-09-15 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pincodes', to='store.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'pincode'), name='unique_product_pincode')],
            },
        ),
    ]
